name: postgres_numeric_support
description: Utility functions to convert from / to postgres numeric type

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  rational: ^2.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.3.0
